// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa-q6Uftb4lUGCKvO4YYLR0FPjnHxVmp4',
    appId: '1:771812337595:android:7c66b5a4acbe71b3f7069e',
    messagingSenderId: '771812337595',
    projectId: 'college-cupid-b53f0',
    storageBucket: 'college-cupid-b53f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpesz_x2MWHBBx8J5nWkX7ekAWwIdnZeE',
    appId: '1:771812337595:ios:5e0738d57850dad1f7069e',
    messagingSenderId: '771812337595',
    projectId: 'college-cupid-b53f0',
    storageBucket: 'college-cupid-b53f0.firebasestorage.app',
    androidClientId: '771812337595-4uc8o3oc51ues0ktsspcotarqqhsfhob.apps.googleusercontent.com',
    iosClientId: '771812337595-j3dv3mao5u57norfgrafkklkk1ogoemk.apps.googleusercontent.com',
    iosBundleId: 'com.swciitg.collegecupid',
  );

}